// Génération de données factices pour CollectionType
const collectionsData: CollectionType[] = [
  {
    _id: "1",
    title: "Collection Printemps",
    description: "Une nouvelle collection pour le printemps.",
    image: "spring-collection.jpg",
    products: [],
  },
  {
    _id: "2",
    title: "Collection Été",
    description: "Une collection chaude pour l'été.",
    image: "summer-collection.jpg",
    products: [],
  },
  {
    _id: "3",
    title: "Collection Automne",
    description: "Une collection chaleureuse pour l'automne.",
    image: "autumn-collection.jpg",
    products: [],
  },
  {
    _id: "4",
    title: "Collection Hiver",
    description: "Une collection chaude pour l'hiver.",
    image: "winter-collection.jpg",
    products: [],
  },
  {
    _id: "5",
    title: "Collection Exclusive",
    description: "Une collection en édition limitée.",
    image: "exclusive-collection.jpg",
    products: [],
  },
];

// Génération de données factices pour ProductType
const productsData: ProductType[] = [
  {
    _id: "1",
    title: "T-shirt Basique",
    description: "Un t-shirt blanc basique.",
    media: ["tshirt-basic.jpg"],
    category: "Vêtements",
    collections: [collectionsData[0]],
    tags: ["basique", "blanc", "t-shirt"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["blanc", "noir"],
    price: 19.99,
    expense: 10.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "2",
    title: "Jeans Slim Fit",
    description: "Un jean slim fit.",
    media: ["jeans-slim-fit.jpg"],
    category: "Vêtements",
    collections: [collectionsData[0], collectionsData[1]],
    tags: ["jeans", "slim fit"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["bleu", "noir"],
    price: 49.99,
    expense: 25.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "3",
    title: "Blouson en Cuir",
    description: "Un blouson en cuir élégant.",
    media: ["leather-jacket.jpg"],
    category: "Vêtements",
    collections: [collectionsData[2], collectionsData[3]],
    tags: ["blouson", "cuir"],
    sizes: ["M", "L", "XL"],
    colors: ["noir"],
    price: 129.99,
    expense: 70.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "4",
    title: "Robe d'Été",
    description: "Une robe légère pour l'été.",
    media: ["summer-dress.jpg"],
    category: "Vêtements",
    collections: [collectionsData[1]],
    tags: ["robe", "été"],
    sizes: ["S", "M", "L"],
    colors: ["rouge", "bleu", "jaune"],
    price: 39.99,
    expense: 20.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "5",
    title: "Sweat à Capuche",
    description: "Un sweat à capuche confortable.",
    media: ["hoodie.jpg"],
    category: "Vêtements",
    collections: [collectionsData[3]],
    tags: ["sweat", "confortable"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["gris", "noir", "bleu"],
    price: 59.99,
    expense: 30.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "6",
    title: "Jupe Plissée",
    description: "Une jupe plissée à la mode.",
    media: ["pleated-skirt.jpg"],
    category: "Vêtements",
    collections: [collectionsData[0], collectionsData[2]],
    tags: ["jupe", "plissée"],
    sizes: ["XS", "S", "M", "L"],
    colors: ["rose", "noir"],
    price: 29.99,
    expense: 15.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "7",
    title: "Chaussures de Sport",
    description: "Chaussures de sport confortables.",
    media: ["sports-shoes.jpg"],
    category: "Chaussures",
    collections: [collectionsData[1], collectionsData[4]],
    tags: ["chaussures", "sport"],
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: ["blanc", "noir", "bleu"],
    price: 89.99,
    expense: 45.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "8",
    title: "Chapeau de Paille",
    description: "Un chapeau de paille élégant.",
    media: ["straw-hat.jpg"],
    category: "Accessoires",
    collections: [collectionsData[1]],
    tags: ["chapeau", "paille"],
    sizes: ["M", "L"],
    colors: ["beige"],
    price: 14.99,
    expense: 7.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "9",
    title: "Écharpe en Laine",
    description: "Une écharpe en laine chaude.",
    media: ["wool-scarf.jpg"],
    category: "Accessoires",
    collections: [collectionsData[3]],
    tags: ["écharpe", "laine"],
    sizes: ["Taille Unique"],
    colors: ["rouge", "vert", "bleu"],
    price: 24.99,
    expense: 12.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "10",
    title: "Chaussettes Confort",
    description: "Une paire de chaussettes confortables.",
    media: ["comfort-socks.jpg"],
    category: "Accessoires",
    collections: [collectionsData[0], collectionsData[2], collectionsData[3]],
    tags: ["chaussettes", "confort"],
    sizes: ["S", "M", "L"],
    colors: ["blanc", "noir", "gris"],
    price: 9.99,
    expense: 5.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "10",
    title: "Chaussettes Confort",
    description: "Une paire de chaussettes confortables.",
    media: ["comfort-socks.jpg"],
    category: "Accessoires",
    collections: [collectionsData[0], collectionsData[2], collectionsData[3]],
    tags: ["chaussettes", "confort"],
    sizes: ["S", "M", "L"],
    colors: ["blanc", "noir", "gris"],
    price: 9.99,
    expense: 5.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "10",
    title: "Chaussettes Confort",
    description: "Une paire de chaussettes confortables.",
    media: ["comfort-socks.jpg"],
    category: "Accessoires",
    collections: [collectionsData[0], collectionsData[2], collectionsData[3]],
    tags: ["chaussettes", "confort"],
    sizes: ["S", "M", "L"],
    colors: ["blanc", "noir", "gris"],
    price: 9.99,
    expense: 5.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "10",
    title: "Chaussettes Confort",
    description: "Une paire de chaussettes confortables.",
    media: ["comfort-socks.jpg"],
    category: "Accessoires",
    collections: [collectionsData[0], collectionsData[2], collectionsData[3]],
    tags: ["chaussettes", "confort"],
    sizes: ["S", "M", "L"],
    colors: ["blanc", "noir", "gris"],
    price: 9.99,
    expense: 5.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: "10",
    title: "Chaussettes Confort",
    description: "Une paire de chaussettes confortables.",
    media: ["comfort-socks.jpg"],
    category: "Accessoires",
    collections: [collectionsData[0], collectionsData[2], collectionsData[3]],
    tags: ["chaussettes", "confort"],
    sizes: ["S", "M", "L"],
    colors: ["blanc", "noir", "gris"],
    price: 9.99,
    expense: 5.0,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Attribution des produits aux collections
/* collections[0].products = [products[0], products[1], products[5], products[9]];
collections[1].products = [products[1], products[4], products[7]];
collections[2].products = [products[2], products[5], products[9]];
collections[3].products = [products[2], products[4], products[8], products[9]];
collections[4].products = [products[7]]; */

// Génération de données factices pour OrderColumnType
const ordersData: OrderColumnType[] = [
  {
    _id: "1",
    customer: "Jean Dupont",
    products: 2,
    totalAmount: 69.98,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "2",
    customer: "Marie Dubois",
    products: 1,
    totalAmount: 49.99,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "3",
    customer: "Alice Martin",
    products: 3,
    totalAmount: 119.97,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "4",
    customer: "Robert Durand",
    products: 2,
    totalAmount: 139.98,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "5",
    customer: "Charles Petit",
    products: 4,
    totalAmount: 189.96,
    createdAt: new Date().toISOString(),
  },
];

// Génération de données factices pour OrderItemType
const orderItemsData: OrderItemType[] = [
  {
    product: productsData[0],
    color: "blanc",
    size: "M",
    quantity: 1,
  },
  {
    product: productsData[1],
    color: "bleu",
    size: "L",
    quantity: 1,
  },
  {
    product: productsData[2],
    color: "noir",
    size: "M",
    quantity: 1,
  },
  {
    product: productsData[3],
    color: "rouge",
    size: "S",
    quantity: 1,
  },
  {
    product: productsData[4],
    color: "gris",
    size: "XL",
    quantity: 2,
  },
  {
    product: productsData[5],
    color: "rose",
    size: "M",
    quantity: 1,
  },
  {
    product: productsData[6],
    color: "blanc",
    size: "42",
    quantity: 1,
  },
  {
    product: productsData[7],
    color: "beige",
    size: "M",
    quantity: 3,
  },
  {
    product: productsData[8],
    color: "rouge",
    size: "Taille Unique",
    quantity: 2,
  },
  {
    product: productsData[9],
    color: "gris",
    size: "M",
    quantity: 4,
  },
];

// Génération de données factices pour CustomerType
const customersData: CustomerType[] = [
  {
    clerkId: "1",
    name: "Jean Dupont",
    email: "jean.dupont@example.com",
  },
  {
    clerkId: "2",
    name: "Marie Dubois",
    email: "marie.dubois@example.com",
  },
  {
    clerkId: "3",
    name: "Alice Martin",
    email: "alice.martin@example.com",
  },
  {
    clerkId: "4",
    name: "Robert Durand",
    email: "robert.durand@example.com",
  },
  {
    clerkId: "5",
    name: "Charles Petit",
    email: "charles.petit@example.com",
  },
  {
    clerkId: "6",
    name: "Émilie Blanc",
    email: "emilie.blanc@example.com",
  },
  {
    clerkId: "7",
    name: "François Noir",
    email: "francois.noir@example.com",
  },
  {
    clerkId: "8",
    name: "Sophie Rouge",
    email: "sophie.rouge@example.com",
  },
  {
    clerkId: "9",
    name: "Lucie Vert",
    email: "lucie.vert@example.com",
  },
  {
    clerkId: "10",
    name: "Pierre Bleu",
    email: "pierre.bleu@example.com",
  },
  {
    clerkId: "11",
    name: "Pierre Bleu",
    email: "pierre.bleu@example.com",
  },
  {
    clerkId: "12",
    name: "Pierre Bleu",
    email: "pierre.bleu@example.com",
  },
];

const eventsData: EventType[] = [
  {
    id: "1",
    title: "Conférence de Motivation avec John Doe",
    description:
      "Un événement inspirant avec le célèbre orateur John Doe. Apprenez à surmonter les obstacles et à atteindre vos objectifs.",
    date: "2024-07-15T09:00:00Z",
    location: "Centre de Conférence Paris, France",
    image: "https://example.com/images/john-doe-conference.jpg",
  },
  {
    id: "2",
    title: "Atelier de Développement Personnel avec Jane Smith",
    description:
      "Participez à un atelier interactif avec Jane Smith pour développer des compétences en leadership et en communication.",
    date: "2024-08-20T14:00:00Z",
    location: "Hôtel Hilton, Lyon, France",
    image: "https://example.com/images/jane-smith-workshop.jpg",
  },
  {
    id: "3",
    title: "Séminaire de Motivation avec Albert Dupont",
    description:
      "Rejoignez Albert Dupont pour un séminaire sur la motivation et la gestion du temps. Améliorez votre productivité et atteignez vos objectifs.",
    date: "2024-09-10T10:00:00Z",
    location: "Palais des Congrès, Marseille, France",
    image: "https://example.com/images/albert-dupont-seminar.jpg",
  },
  {
    id: "4",
    title: "Conférence Internationale sur la Motivation",
    description:
      "Une conférence réunissant des experts du monde entier pour discuter des dernières recherches et techniques en matière de motivation.",
    date: "2024-10-05T09:00:00Z",
    location: "Centre International de Conférence, Nice, France",
    image: "https://example.com/images/international-conference.jpg",
  },
  {
    id: "5",
    title: "Webinaire de Motivation en Ligne",
    description:
      "Participez à notre webinaire en ligne pour apprendre des stratégies de motivation efficaces depuis le confort de votre domicile.",
    date: "2024-11-12T18:00:00Z",
    location: "En ligne",
    image: "https://example.com/images/online-webinar.jpg",
  },
  {
    id: "6",
    title: "Rencontre avec les Leaders de la Motivation",
    description:
      "Une occasion unique de rencontrer et d'interagir avec les leaders du domaine de la motivation. Apprenez de leurs expériences et de leurs succès.",
    date: "2024-12-01T15:00:00Z",
    location: "Grand Hôtel, Bordeaux, France",
    image: "https://example.com/images/motivation-leaders-meeting.jpg",
  },
  {
    id: "7",
    title: "Conférence sur la Motivation des Jeunes",
    description:
      "Un événement dédié à la motivation des jeunes, avec des ateliers et des sessions de mentorat pour les aider à atteindre leur plein potentiel.",
    date: "2024-07-25T10:00:00Z",
    location: "Université de Strasbourg, Strasbourg, France",
    image: "https://example.com/images/youth-motivation-conference.jpg",
  },
  {
    id: "8",
    title: "Sommet de la Motivation et du Bien-être",
    description:
      "Un sommet axé sur la motivation et le bien-être personnel, avec des experts en santé mentale et en développement personnel.",
    date: "2024-08-15T09:00:00Z",
    location: "Centre de Bien-être, Lille, France",
    image: "https://example.com/images/motivation-wellness-summit.jpg",
  },
  {
    id: "9",
    title: "Atelier de Motivation pour Entrepreneurs",
    description:
      "Un atelier destiné aux entrepreneurs pour les aider à rester motivés et à surmonter les défis du monde des affaires.",
    date: "2024-09-30T13:00:00Z",
    location: "Incubateur de Startups, Toulouse, France",
    image: "https://example.com/images/entrepreneur-motivation-workshop.jpg",
  },
  {
    id: "10",
    title: "Session de Coaching en Motivation avec Pierre Martin",
    description:
      "Une session de coaching en petit groupe avec Pierre Martin, pour recevoir des conseils personnalisés et booster votre motivation.",
    date: "2024-10-20T14:00:00Z",
    location: "Salle de Conférence, Nantes, France",
    image: "https://example.com/images/pierre-martin-coaching.jpg",
  },
];

export {
  collectionsData,
  productsData,
  ordersData,
  orderItemsData,
  customersData,
  eventsData,
};
